name: Hotfix CI

on:
  pull_request:
    branches: [production]
    types: [closed]

jobs:
  auto-pr-hotfix:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Open hotfix PR to main branch
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.head_ref }}
          destination_branch: "main"
          pr_title: ":dna: Auto PR from ${{ github.head_ref }} into main"
          pr_body: "Automatically created PR from branch: ${{ github.head_ref }}([#${{github.event.number}}](https://github.com/${{github.repository}}/pull/${{github.event.number}})) which has already been merged into mainnet"
          pr_reviewer: "poomthiti"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Open hotfix PR to test branch
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.head_ref }}
          destination_branch: "test"
          pr_title: ":dna: Auto PR from ${{ github.head_ref }} into test"
          pr_body: "Automatically created PR from branch: ${{ github.head_ref }}([#${{github.event.number}}](https://github.com/${{github.repository}}/pull/${{github.event.number}})) which has already been merged into mainnet"
          pr_reviewer: "poomthiti"
          github_token: ${{ secrets.GITHUB_TOKEN }}
