name: Hotfix CI

on:
  pull_request:
    branches: [production]
    types: [closed]

jobs:
  auto-pr-hotfix:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Open hotfix PR to main branch
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.head_ref }} # If blank, default: triggered branch
          destination_branch: "main" # If blank, default: master
          pr_title: "Auto PR from ${{ github.head_ref }} into main" # Title of pull request
          pr_body: "Automatically created PR from branch: ${{ github.head_ref }}(${{github.event.number}}) which has already been merged into mainnet" # Full markdown support, requires pr_title to be set
          pr_reviewer: "poomthiti" # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Open hotfix PR to test branch
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.head_ref }} # If blank, default: triggered branch
          destination_branch: "test" # If blank, default: master
          pr_title: "Auto PR from ${{ github.head_ref }} into test" # Title of pull request
          pr_body: "Automatically created PR from branch: ${{ github.head_ref }}(${{github.event.number}}) which has already been merged into mainnet" # Full markdown support, requires pr_title to be set
          pr_reviewer: "poomthiti" # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}
